subtitle_viewer/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('viewer/', include('viewer.urls', namespace='viewer')),
    path('admin/', admin.site.urls),

]

viewer/urls.py
from django.conf.urls import url
from . import views

app_name = 'viewer'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^by_folder/$', views.by_folder, name='by_folder'),
    url(r'^by_withsubs/$', views.by_withsubs, name='by_withsubs'),
    url(r'^by_withoutsubs/$', views.by_withoutsubs, name='by_withoutsubs'),
    url(r'^refresh_list/$', views.refresh_list, name='refresh_list'),
    url(r'^detail/(?P<m_detail>.+?)/$', views.detail_view, name='detail_view'),
    url(r'^delete/(?P<d_file>.+?)/$', views.delete_file, name='delete_view'),
    url(r'^download-subtitle/(?P<f_name>.+?)/$', views.download_view, name='download_view'),
]

viewer/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class movie_name(models.Model):
    id = models.AutoField(primary_key=True)
    moviename = models.CharField(max_length=100, unique=True)
    has_subtitle = models.BooleanField(default=False)

    def __str__(self):
        return str(self.moviename)

    def get_absolute_url(self):
        return reverse('viewer:detail_view', kwargs={'m_detail': self.moviename})

class file_list(models.Model):
    id = models.AutoField(primary_key=True)
    m_name = models.ForeignKey(movie_name, on_delete=models.CASCADE)
    file_name = models.CharField(max_length=50, unique=True)
    file_path = models.CharField(max_length=80, unique=True)
    file_size = models.DecimalField(max_digits=30, decimal_places=2)
    file_date = models.DateField()
    is_subtitle = models.BooleanField(default=False)

    def __str__(self):
        return str(self.file_name)

    def save(self, *args, **kwargs):
        MB = int(1048576)
        self.file_size = (self.file_size/MB)
        super(file_list, self).save(*args, **kwargs)

class settings(models.Model):
    folder_path = models.CharField(max_length=50, unique=True)
    enabled = models.BooleanField(default=False)

viewer/views.py
from django.shortcuts import render, get_object_or_404
from .my_modules import file_lister, file_delete, downloader
from .models import movie_name, file_list, settings


# Create your views here.

## ff om te testen
def app_folder_setting():
    data = settings.objects.all()
    for x in data:
        return(x.folder_path)
###
path = app_folder_setting()

def index(request):
    list = []
    context = {'list':list}
    return render(request, 'viewer/index.html', context)

def by_withsubs(request):
    identifier = 'films met subs'
    list = movie_name.objects.filter(has_subtitle = True).order_by("moviename")
    context = {'list':list, 'identifier':identifier}
    return render(request, 'viewer/resultview.html', context)

def by_withoutsubs(request):
    identifier = 'films zonder subs'
    list = movie_name.objects.filter(has_subtitle=False).order_by("moviename")
    context = {'list':list, 'identifier':identifier}
    return render(request, 'viewer/resultview.html', context)

def by_folder(request):
    identifier = 'alle films'
    all_movies = movie_name.objects.all().order_by("moviename")
    context = {'all_movies':all_movies, 'identifier':identifier}
    return render(request, 'viewer/allmovies.html', context)

def detail_view(request,m_detail):
    selected_movie = file_list.objects.filter(m_name__moviename__icontains=m_detail.replace("-"," "))
    context = {'selected_movie':selected_movie, 'm_detail':m_detail}
    return render(request,'viewer/detail_view.html', context)

def refresh_list(request):
    file_lister(path)

    return render(request,'viewer/index.html')


def delete_file(request, d_file):
    file_to_delete = d_file
    file_delete(d_file)
    context = {'file_to_delete': file_to_delete}
    return render(request, 'viewer/deleted.html', context)

def download_view(request, f_name):
    subtitle_to_search = f_name
    downloader(f_name)
    context = {'subtitle_to_search': subtitle_to_search}
    return render(request, 'viewer/downloaded.html', context)

#to_check = file_lister(path)

viewer/templates/viewer/allmovies.html
{% extends 'viewer/index.html' %}

{% block body1 %}
      <div class="col-sm-9 col-sm-offset-3 col-md-9 col-md-offset-2 main">
          <h1 class="page-header">lijst van {{ identifier }}</h1>
          <div class="row placeholders">

      <div class="table-responsive">
      <table class="table table-hover table-striped">
      <thead>
            <tr >
                <th class="text-center"; bgcolor=" #333333"; style="color:white"> Nummer </th>
                <th bgcolor=" #333333"; style="color:white"> Film </th>
                <th class="text-center"; bgcolor=" #333333"; style="color:white"> Heeft ondertittels </th>
            </tr>
       </thead>
       <tbody>
            {% for x in all_movies %}
                <tr class="info">
                        <td align="center">{{ forloop.counter }}</td>
                        <td>{{ x.moviename }}</td>
                        <td align="center">{% if x.has_subtitle == True %}&#9989;{% else %}&#10060;{% endif %}</td>
                </tr>
            {% endfor %}
       </tbody>
       </div>
{% endblock %}

viewer/templates/viewer/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>subtitle list</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'viewer/css/bootstrap.min.css' %}" type = "text/css"/>
</head>


<nav class="navbar navbar-default navbar-static-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Viewer</a>
        </div>
        <ul class="nav navbar-nav">
            <li><a href="/viewer">test1</a></li>
            <li><a href="/viewer">test2</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'viewer:refresh_list' %}">refresh folders</a></li>
            <li><a href="/admin">Admin</a></li>
        </ul>
    </div>
</nav>




<div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">

{% block body %}
{% endblock %}
        </div>

      </div>
</div>
{% block body1 %}
{% endblock %}
  </body>
</html>


<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

viewer/templates/viewer/deleted.html
{% extends 'viewer/index.html' %}

{% block body1 %}
      <div class="col-sm-9 col-sm-offset-3 col-md-9 col-md-offset-2 main">
          <h1 class="page-header">deleten van file {{ file }}</h1>
          <div class="row placeholders">


              <h1>DELETED {{ file_to_delete }}</h1>
{% endblock %}

viewer/templates/viewer/detail_view.html
{% extends 'viewer/index.html' %}

{% block body1 %}
      <div class="col-sm-9 col-sm-offset-3 col-md-9 col-md-offset-2 main">
          <h1 class="page-header">details van {{ m_detail }}</h1>
          <div class="row placeholders">

      <div class="table-responsive">
      <table class="table table-hover table-striped">
      <thead>
            <tr >
                <th class="text-center"; bgcolor=" #333333"; style="color:white"> Nummer </th>
                <th bgcolor=" #333333"; style="color:white"> Film </th>
                <th bgcolor=" #333333"; style="color:white"> bestandsnaam </th>
                <th bgcolor=" #333333"; style="color:white"> grootte </th>
                <th bgcolor=" #333333"; style="color:white"> datum </th>
                <th class="text-center" bgcolor=" #333333"; style="color:white"> subtitle search </th>
                <th class="text-center" bgcolor=" #333333"; style="color:white"> DELETE </th>
            </tr>
       </thead>
       <tbody>
            {% for x in selected_movie %}
                <tr class="info">
                        <td align="center">{{ forloop.counter }}</td>
                        <td>{{ x.m_name }}</td>
                        <td>{{ x.file_name }}</td>
                        <td>{{ x.file_size }} MB</td>
                        <td>{{ x.file_date }}</td>
                        <td align="center"> <a href="{% url 'viewer:download_view' x.file_name %}"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></a></td>
                        <td align="center"> <a href="{% url 'viewer:delete_view' x.file_name %}">&#9940</a></td>
                </tr>
            {% endfor %}
       </tbody>
       </div>
{% endblock %}

viewer/templates/viewer/downloaded.html
{% extends 'viewer/index.html' %}

{% block body1 %}
      <div class="col-sm-9 col-sm-offset-3 col-md-9 col-md-offset-2 main">
          <h1 class="page-header">downloaden van file {{ file }}</h1>
          <div class="row placeholders">


              <h1>Searched for {{ subtitle_to_search }}</h1>
{% endblock %}

viewer/templates/viewer/index.html
{% extends 'viewer/base.html' %}

{% block body %}
<div class="btn-group-vertical" role="group">
    <div class="btn-group" role="group">
        <button id="btnGroupVerticalDrop1" type="button" class="btn btn-default btn-lg dropdown-toggle" data-toggle="dropdown"> filter <span class="caret"></span> </button>
        <ul class="dropdown-menu" aria-labelledby="btnGroupVerticalDrop1">
            <li><a href="{% url 'viewer:by_withsubs' %}">containing subs</a></li>
            <li><a href="{% url 'viewer:by_withoutsubs' %}">not containing subs</a></li>
            <li><a href="{% url 'viewer:by_folder' %}">by folder</a></li>
        </ul>
    </div>
</div>

{% endblock %}

{% block body1 %}
<div class="col-sm-9 col-sm-offset-3 col-md-9 col-md-offset-2 main">
          <h1 class="page-header">lijst om na te kijken</h1>
          <div class="row placeholders">

      <div class="table-responsive">
      <table class="table table-hover table-striped">
      <thead>
            <tr >
                <th bgcolor=" #333333"; style="color:white"> Number </th>
                <th bgcolor=" #333333"; style="color:white"> foldernaam </th>
            </tr>
       </thead>
       <tbody>
            {% for x in list %}
                <tr class="info">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ x }}</td>
                </tr>
            {% endfor %}
       </tbody>
       </div>
{% endblock %}

viewer/templates/viewer/resultview.html
{% extends 'viewer/index.html' %}

{% block body1 %}
      <div class="col-sm-9 col-sm-offset-3 col-md-9 col-md-offset-2 main">
          <h1 class="page-header">lijst van {{ identifier }}</h1>
          <div class="row placeholders">

      <div class="table-responsive">
      <table class="table table-hover table-striped">
      <thead>
            <tr >
                <th class="text-center"; bgcolor=" #333333"; style="color:white"> Nummer </th>
                <th bgcolor=" #333333"; style="color:white"> Filenaam </th>
            </tr>
       </thead>
       <tbody>
            {% for x in list %}
                <tr class="info">
                        <td align="center">{{ forloop.counter }}</td>
                        <td><a href="{{ x.get_absolute_url }}">{{ x }}</a></td>
                </tr>
            {% endfor %}
       </tbody>
       </div>
{% endblock %}